# Generated by Django 4.1.6 on 2023-02-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MskContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=150, verbose_name='Оператор')),
                ('support', models.CharField(max_length=150, verbose_name='Тех. поддержка')),
                ('work', models.CharField(max_length=150, verbose_name='Трудоустройство')),
                ('bot_1', models.CharField(max_length=150, verbose_name='Бот №1')),
                ('bot_2', models.CharField(max_length=150, verbose_name='Бот №2')),
                ('bot_3', models.CharField(max_length=150, verbose_name='Бот №3')),
                ('bot_4', models.CharField(max_length=150, verbose_name='Бот №4')),
                ('bot_5', models.CharField(max_length=150, verbose_name='Бот №5')),
                ('bot_account', models.CharField(max_length=150, verbose_name='Бот-аккаунт')),
            ],
            options={
                'verbose_name': 'Контакты Москва',
            },
        ),
    ]
