# Generated by Django 4.1.6 on 2023-02-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_url', models.CharField(max_length=150, verbose_name='Ссылка на главной странице')),
            ],
            options={
                'verbose_name': 'Ссылка на главной странице',
                'verbose_name_plural': 'Ссылка на главной странице',
            },
        ),
        migrations.CreateModel(
            name='SpbContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=150, verbose_name='Оператор')),
                ('support', models.CharField(max_length=150, verbose_name='Тех. поддержка')),
                ('work', models.CharField(max_length=150, verbose_name='Трудоустройство')),
                ('bot_1', models.CharField(max_length=150, verbose_name='Бот №1')),
                ('bot_2', models.CharField(max_length=150, verbose_name='Бот №2')),
                ('bot_3', models.CharField(max_length=150, verbose_name='Бот №3')),
                ('bot_4', models.CharField(max_length=150, verbose_name='Бот №4')),
                ('bot_5', models.CharField(max_length=150, verbose_name='Бот №5')),
            ],
            options={
                'verbose_name': 'Контакты Спб',
                'verbose_name_plural': 'Контакты Спб',
            },
        ),
        migrations.AlterModelOptions(
            name='mskcontacts',
            options={'verbose_name': 'Контакты Москва', 'verbose_name_plural': 'Контакты Москва'},
        ),
    ]
